=== Data-to-Insight-Center/sead-virtual-archive/DataConservancyCode/model/dcs-model/src/main/resources/schema/dcp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<schema targetNamespace="http://dataconservancy.org/schemas/dcp/1.0"
  elementFormDefault="qualified" attributeFormDefault="unqualified"
  xmlns="http://www.w3.org/2001/XMLSchema" xmlns:dcp="http://dataconservancy.org/schemas/dcp/1.0"
  xmlns:dc="http://purl.org/dc/elements/1.1/creator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!-- 
    $Id: dcp.xsd 2954 2012-02-27 19:38:56Z hvu13 $
    $URL: https://scm.dataconservancy.org/svn/model/trunk/dcs-model/src/main/resources/schema/dcp.xsd $
  -->
  
  <element name="dcp" type="dcp:dcpContainerType">
    <annotation>
      <documentation> 
          $Id: dcp.xsd 2954 2012-02-27 19:38:56Z hvu13 $
          $URL: https://scm.dataconservancy.org/svn/model/trunk/dcs-model/src/main/resources/schema/dcp.xsd $
      </documentation>
    </annotation>
  </element>

  <complexType name="dcpContainerType">
    <sequence>
      <element name="DeliverableUnits" type="dcp:deliverableUnitContainerType"
        maxOccurs="1" minOccurs="0">
      </element>
      <element name="Collections" type="dcp:collectionContainerType"
        maxOccurs="1" minOccurs="0">
      </element>
      <element name="Manifestations" type="dcp:manifestationContainerType"
        maxOccurs="1" minOccurs="0">
      </element>
      <element name="Files" type="dcp:fileContainerType"
        maxOccurs="1" minOccurs="0">
      </element>
      <element name="Events" type="dcp:eventContainerType"
        maxOccurs="1" minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="deliverableUnitType">
    <complexContent>

      <extension base="dcp:entityType">
        <sequence>
          <element name="collection" type="dcp:entityRef"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="parent" type="dcp:entityRef" maxOccurs="unbounded"
            minOccurs="0">
          </element>
          <element name="type" type="string" maxOccurs="unbounded"
            minOccurs="0">
          </element>
          <element name="title" type="string" maxOccurs="1"
            minOccurs="1">
          </element>
          <element name="creator" type="string" maxOccurs="unbounded"
            minOccurs="0">
          </element>
          <element name="subject" type="string" maxOccurs="unbounded"
            minOccurs="0">
          </element>
          <element name="rights" type="string" maxOccurs="1"
            minOccurs="0">
          </element>
          <element name="formerExternalRef" type="string"
            maxOccurs="unbounded" minOccurs="0">
            <annotation>
              <documentation>
                Any previous reference used to identify
                the
                Deliverable Unit before the it was
                transfered to the
                repository.
							</documentation>
            </annotation>
          </element>
          <element name="digitalSurrogate" type="boolean"
            maxOccurs="1" minOccurs="0"></element>
          <element name="metadata" type="dcp:metadataBlobType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="relationship" type="dcp:relatedEntityType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
        </sequence>
        <attribute name="lineageId" type="anyURI" use="optional"></attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="collectionContainerType">
    <sequence>
      <element name="Collection" type="dcp:collectionType"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="deliverableUnitContainerType">
    <sequence>
      <element name="DeliverableUnit" type="dcp:deliverableUnitType"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="collectionType">
    <complexContent>
      <extension base="dcp:entityType">
        <sequence>
          <element name="parent" type="dcp:entityRef" maxOccurs="1"
            minOccurs="0">
          </element>
          <element name="type" type="string" maxOccurs="unbounded"
            minOccurs="0">
          </element>
          <element name="title" type="string" maxOccurs="1"
            minOccurs="1">
          </element>
          <element name="creator" type="string" maxOccurs="unbounded"
            minOccurs="0">
          </element>
                    <element name="subject" type="string" maxOccurs="unbounded" minOccurs="0"></element>
                    <element name="metadata" type="dcp:metadataBlobType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="fileContainerType">
    <sequence>
      <choice maxOccurs="unbounded" minOccurs="0">
        <element name="File" type="dcp:fileType" maxOccurs="unbounded"
          minOccurs="0">
        </element>
        <element name="EmbeddedFile" type="dcp:embeddedFileType"
          maxOccurs="unbounded" minOccurs="0">
        </element>

      </choice>
    </sequence>
  </complexType>

  <complexType name="fileType">
    <complexContent>
      <extension base="dcp:entityType">

        <sequence>
          <element name="fileName" type="string" maxOccurs="1"
            minOccurs="1">
            <annotation>
              <documentation>
                The name of the file, outside of any path
                context
              </documentation>
            </annotation>
          </element>
          <element name="extant" type="boolean" maxOccurs="1"
            minOccurs="1">
            <annotation>
              <documentation>
                Whether the file exists (or should) in the
                dcs for
                preservation
              </documentation>
            </annotation>
          </element>
          <element name="size" type="long" maxOccurs="1"
            minOccurs="0">
          </element>
          <element name="fixity" type="dcp:fixityType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="format" type="dcp:formatType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="valid" type="boolean" maxOccurs="1"
            minOccurs="0">
          </element>
          <element name="metadata" type="dcp:metadataBlobType"
            maxOccurs="unbounded" minOccurs="0">
          </element>         
        </sequence>
        <attribute name="src" type="anyURI" use="optional">
          <annotation>
            <documentation>
              URL which locates the content of the file.
              For
              internally packaged files, this may be a
              file URI (eg
              file:///data/files/1.png)
						</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="manifestationContainerType">
    <sequence>
      <element name="Manifestation" type="dcp:manifestationType"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </sequence>
  </complexType>


  <attributeGroup name="entityAttributes">
    <attribute name="id" type="anyURI">
      <annotation>
        <documentation>
          URI which uniquely identifies a DCS entity. It
          must
          not be assumed to be a resolvable URL. Elements
          within the
          DCP
          document may refer to an entity
          unambiguously by its id.
        </documentation>
      </annotation>
    </attribute>
  </attributeGroup>

  <complexType name="entityRef">
    <attribute name="ref" type="anyURI" use="required">
      <annotation>
        <documentation>
          URI which unambiguously represents the identity
          of
          an
          entity. This may refer an entity defined in the
          DCP
          document or
          elsewhere (e.g. in the DCS)
				</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="metadataBlobType">
    <sequence>
      <any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="schemaURI" type="anyURI" use="optional">
      <annotation>
        <documentation>
          Schema URI of the contained or referenced
          metadata,
          if applicable.
				</documentation>
      </annotation>
    </attribute>
    <attribute name="ref" type="anyURI" use="optional">
      <annotation>
        <documentation>
          If metadata is represented in a File entity, it
          may
          be referenced here as containing a blob of relevant
          metadata
				</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="relatedEntityType">
    <complexContent>
      <extension base="dcp:entityRef">
        <attribute name="rel" use="required">
          <annotation>
            <documentation>Relationship type</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="alternateResourceIdentifierType">
    <sequence>
      <element name="authorityId" minOccurs="0" maxOccurs="1" />
      <element name="typeId" minOccurs="0" maxOccurs="1"/>
      <element name="idValue" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>
  
  <complexType name="entityType">
    <sequence>
      <element name="alternateIdentifier" type="dcp:alternateResourceIdentifierType" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="id" type="anyURI" use="required"></attribute>
  </complexType>

  <complexType name="manifestationType">
    <complexContent>
      <extension base="dcp:entityType">
        <sequence>
          <element name="deliverableUnit" type="dcp:entityRef"
            maxOccurs="1" minOccurs="1">
          </element>
          <element name="technicalEnvironment" type="string"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="type" type="string" maxOccurs="1"
            minOccurs="0"></element>
          <element name="manifestationFile" type="dcp:manifestationFileType"
            maxOccurs="unbounded" minOccurs="0">
          </element>
          <element name="metadata" type="dcp:metadataBlobType"
            maxOccurs="unbounded" minOccurs="0">
          </element>        
        </sequence>
        <attribute name="dateCreated" type="string" use="optional">
          <annotation>
            <documentation>Date on which the manifestation is created</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="fixityType">
    <simpleContent>
      <extension base="string">
        <attribute name="algorithm" type="string"></attribute>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="formatType">
    <sequence>
      <element name="id" type="dcp:formatIdType" maxOccurs="1"
        minOccurs="1">
      </element>
      <element name="name" type="string" maxOccurs="1"
        minOccurs="0"></element>
      <element name="version" type="string" maxOccurs="1"
        minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="formatIdType">
    <simpleContent>
      <extension base="string">
        <attribute name="scheme" type="anyURI"></attribute>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="eventContainerType">
    <sequence>
      <element name="Event" type="dcp:eventType" maxOccurs="unbounded"
        minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="eventType">
    <complexContent>
      <extension base="dcp:entityType">
        <sequence>
          <element name="eventType" type="string" maxOccurs="1"
            minOccurs="1">
          </element>
          <element name="eventDate" type="dateTime" maxOccurs="1"
            minOccurs="1">
          </element>
          <element name="eventTarget" type="dcp:entityRef"
            maxOccurs="unbounded" minOccurs="1"></element>
          <element name="eventDetail" type="string" maxOccurs="1"
            minOccurs="0">
          </element>
          <element name="eventOutcome" type="string" maxOccurs="1"
            minOccurs="0">
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="embeddedFileType">
    <complexContent>
      <extension base="dcp:fileType">
        <sequence>
          <element name="inFile" type="dcp:entityRef" maxOccurs="1"
            minOccurs="1"></element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="manifestationFileType">
    <complexContent>
      <extension base="dcp:entityRef">
        <sequence>
          <element name="path" type="string" maxOccurs="1"
            minOccurs="0"></element>
          <element name="relationship" type="dcp:relatedEntityType"
            maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
</schema>

=== Data-to-Insight-Center/sead-virtual-archive/DataConservancyCode/model/dcs-model-builder-tests/src/main/resources/org/dataconservancy/model/builder/sip/DcpSip_TESTCASE_004.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!--
  Represents a minimal DCP SIP which is invalid according to the schema.
-->
<dcp xmlns="http://dataconservancy.org/schemas/dcp/1.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://dataconservancy.org/schemas/dcp/1.0 file:/Users/esm/dc-svn/model/trunk/dcs-model/src/main/resources/schema/dcp.xsd">
  
  <DeliverableUnits>
    <DeliverableUnit>
      <collection ref="urn:Collection:1"/>
      <title>Discovery: LP</title>
      <type>music album</type>
      <creator>Discovery</creator>
      <subject>music</subject>
      <formerExternalRef><![CDATA[http://www.amazon.com/LP/dp/B002EAP0FE/ref=sr_shvl_album_1?ie=UTF8&qid=1276130789&sr=301-1]]></formerExternalRef>
      <digitalSurrogate>true</digitalSurrogate>
      
      <relationship rel="cover art" ref="http://www.amazon.com/gp/product/images/B002EAP0FE/ref=dp_image_0?ie=UTF8&amp;n=163856011&amp;s=dmusic"/>
    </DeliverableUnit>
  </DeliverableUnits>
  
</dcp>

=== Data-to-Insight-Center/sead-virtual-archive/DataConservancyCode/dcs-ui/dcs-ui-resources/src/main/resources/org/dataconservancy/ui/objects/sip/MdF_ISO19115_SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<dcp xmlns="http://dataconservancy.org/schemas/dcp/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://dataconservancy.org/schemas/dcp/1.0 dcp.xsd ">

  <DeliverableUnits>
    <DeliverableUnit id="http://dataconservancy.org/dcs-reserved:22345">

      <type>dc:profile:type\metadataFormat</type>
      <title>ISO 19115</title>
      <creator>Data Conservancy</creator>
      <subject>Metadata Format Definition</subject>
      <formerExternalRef>dc:format:metadata\ISO19115</formerExternalRef>

      <!--
        An example of metadata that exists as a file. This can be used but there is no current need.
      -->
      <!-- <metadata ref="urn:sdss:12345/metadata" /> -->

    </DeliverableUnit>
  </DeliverableUnits>


  <!-- Format Definitions can be placed in a system collection but there is no current need.
  <Collections>
    <Collection id="http://dataconservancy.org/dcs-reserved:12344">
      <title>title</title>
    </Collection>
  </Collections>
  -->


  <Manifestations>
    <Manifestation id="http://dataconservancy.org/dcs-reserved:22343">
      <deliverableUnit ref="http://dataconservancy.org/dcs-reserved:22345" />
      <manifestationFile ref="http://dataconservancy.org/dcs-reserved:22346/FORMAT_DEFINITION_FILE">
        <!-- <path>/scans/5/</path> -->
      </manifestationFile>
    </Manifestation>
  </Manifestations>


  <Files>

    <!--
      An example of a format used for seeding the DCS that is original to the DCS
      or may be a wrapper for a format defined somewhere else. Only the registration
      is required but additional information may be stored in the associated file.
    -->
    <File id="http://dataconservancy.org/dcs-reserved:12346/FORMAT_DEFINITION_FILE" src="object005">
      <fileName>MdF_ISO19115_FILE_1.xml</fileName>
      <extant>true</extant>
      <fixity algorithm="md5">fe5b3b4f78b9bf3ae21cd52c2f349174</fixity>
      <!-- Fails to parse when there is exactly one dc:xxxx in the content. It thinks its a namespace.
      <format>
        <id scheme="http://www.dataconservancy.org/formats/">dc:format</id>
      </format>
      -->
      <format>
        <id scheme="http://www.dataconservancy.org/formats/">dc:format:metaformat:1</id>
      </format>
      <format>
        <id scheme="http://www.iana.org/assignments/media-types/">text/xml</id>
      </format>
    </File>

  </Files>
</dcp>

=== Data-to-Insight-Center/sead-virtual-archive/DataConservancyCode/model/dcs-model-builder-tests/src/main/resources/org/dataconservancy/model/builder/sip/DcpSip_TESTCASE_006.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<dcp xmlns="http://dataconservancy.org/schemas/dcp/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://dataconservancy.org/schemas/dcp/1.0 dcp.xsd ">

  <DeliverableUnits>
    <DeliverableUnit id="urn:sdss:12345">

      <!--  The collection exists, and this is its DCS identifier -->
      <collection ref="http://dataconservancy.org/collections/SDSS_run_5" />

      <title>SDSS file 12345</title>
      <creator>Astrophysical Research Consortium (ARC)</creator>
      <subject>Astronomy</subject>
      <formerExternalRef>http://das.sdss.org/blahblahblah...</formerExternalRef>

      <!-- An example of metadata inline -->
      <metadata schemaURI="http://sdss.org/metadata/astroSchema.example.xsd">
        <md xmlns:astro="http://sdss.org/astro">
          <astro:skyCoverage>all of it</astro:skyCoverage>
          <astro:enfOfWorldFactor>-1</astro:enfOfWorldFactor>
        </md>
      </metadata>

      <!--
        An example of metadata that exists as a file, in this case it is
        submitted in the SIP
      -->
      <metadata ref="urn:sdss:12345/metadata" />

    </DeliverableUnit>
  </DeliverableUnits>


  <Collections>
    <Collection id="http://tempuri.org">
      <title>title</title>
    </Collection>
  </Collections>


  <Manifestations>
    <Manifestation id="urn:sdss:12345/manifestation">
      <deliverableUnit ref="urn:sdss:12345" />
      <manifestationFile ref="urn:sdss:12345/FITS_FILE">
        <path>/scans/5/</path>
      </manifestationFile>
    </Manifestation>
  </Manifestations>


  <Files>

    <!--
      An example of an externally located file that will not be
      preserved in the DCS archive (e.g. DCS will curate it, but not
      transfer the bytes to the archive. It will remain an external
      reference)
    -->
    <File id="urn:sdss:12345/FITS_FILE" src="http://sdss.org/files/fits/12345.fits">
      <fileName>12345.fits</fileName>
      <extant>false</extant>
      <format>
        <id scheme="http://www.nationalarchives.gov.uk/PRONOM/">x-fmt/383</id>
        <name>FITS</name>
        <version>3.0</version>
      </format>
    </File>

    <!--
      An example of a file that has been previously uploaded to the DCS
      ingest API. The src value was returned by the ingest API and used
      here.
    -->
    <File id="urn:sdss:12345/metadata" src="urn:dcs:uploads/0x440">
      <fileName>fitsDerivedMetadata.csv</fileName>
      <extant>true</extant>
      <fixity algorithm="md5">fe5b3b4f78b9bf3ae21cd52c2f349174</fixity>
      <format>
        <id scheme="http://www.nationalarchives.gov.uk/PRONOM/">x-fmt/18</id>
      </format>
      <format>
        <id scheme="http://www.iana.org/assignments/media-types/">text/csv</id>
      </format>
    </File>

  </Files>
</dcp>

=== Data-to-Insight-Center/sead-virtual-archive/DataConservancyCode/dcs-ingest/dcs-ingest-services/src/test/resources/org/dataconservancy/dcs/ingest/services/updatingSips/ArchiveBranchingSip.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<dcp xmlns="http://dataconservancy.org/schemas/dcp/1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://dataconservancy.org/schemas/dcp/1.0 file:/Users/esm/dc-svn/model/trunk/dcs-model/src/main/resources/schema/dcp.xsd">

  <DeliverableUnits>
    <!-- opaque ID for new DU -->
    <DeliverableUnit id="urn:DU_02_Update">
      <title>SDSS file 12345b</title>
      <relationship rel="urn:dataconservancy.org:rel/isSuccessorOf" ref="http://dataconservancy.org/du1"/>
    </DeliverableUnit>
  </DeliverableUnits>

  <Manifestations>
    <Manifestation id="urn:DU_01_Update/manifestation2">
      <deliverableUnit ref="urn:DU_02_Update" />
      <manifestationFile ref="urn:file:03">
      </manifestationFile>
    </Manifestation>
  </Manifestations>

  <Files>
    <File id="urn:file:03" src="http://www.uscis.gov/files/form/i-9.pdf">
      <fileName>form/i-9.pdf</fileName>
      <extant>true</extant>
    </File>
  </Files>

</dcp>

=== Data-to-Insight-Center/sead-virtual-archive/SEAD-VA-extensions/dcs-archive/sead-archive-impl-s3/src/test/resources/ManyRelationships.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2013 The Trustees of Indiana University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~       http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<dcp xmlns="http://dataconservancy.org/schemas/dcp/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://dataconservancy.org/schemas/dcp/1.0 dcp.xsd ">
  <DeliverableUnits>
    <DeliverableUnit id="example:/DeliverableUnit/child">
        <title>DUtitle</title>
        <parent
                ref="example:/DeliverableUnit/parent" />
    </DeliverableUnit>
      <DeliverableUnit id="example:/DeliverableUnit/parent">
          <title>ParentDU</title>
      </DeliverableUnit>
  </DeliverableUnits>

  <Manifestations>
    <Manifestation id="example:/Manifestation/1">
      <deliverableUnit ref="example:/DeliverableUnit/child" />
      <manifestationFile ref="example:/File/Content/1" />
    </Manifestation>
  </Manifestations>
  <Files>
    <File id="example:/File/Content/1" src="/home/kavchand/Downloads/654">
      <fileName>fileName</fileName>
      <extant>true</extant>
    </File>
    </Files>
</dcp>
